version: '3.7'

volumes:
  pg-data: {}

services:
  # Postgres Database (SQL)
  database:
    container_name: django-db
    hostname: db
    image: postgis/postgis:14-3.3-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - '5435:5432'
    environment:  # change these vars as DATABASE_URL in your .env file
      - POSTGRES_DB=django
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - db-net

  # Django
  webapp:
    env_file: ./django_api_example/.env
    image: school_man:dev
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: []
    command: >
      bash -c 'while !</dev/tcp/db/5432 || !</dev/tcp/redis/6379; do sleep 1; done;
      python manage.py runserver 0.0.0.0:8000'
    volumes:
        - ./django_api_example:/app/django_api_example
    ports:
      - '8000:8000'
    depends_on:
      - database
      - redis
    networks:
      - db-net

  redis:
    hostname: redis
    container_name: redis
    restart: always
    image: redis:alpine
    expose:
      - 6379
    ports:
      - '6379:6379'
    networks:
      - db-net

networks:
  db-net:
    driver: bridge