# Generated by Django 3.2 on 2022-01-15 11:45

from django.db import migrations, models
import django.db.models.deletion
import school_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_student', models.IntegerField(default=3000, verbose_name='Maximum number of student per year')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=60)),
                ('student_id', models.CharField(default=school_manager.models.id_generator, editable=False, max_length=20, unique=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_manager.school')),
            ],
        ),
    ]
