# Generated by Django 3.2 on 2022-01-16 14:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_manager', '0002_auto_20220116_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('PRE', 'Preschool'), ('ELE', 'Elementary'), ('MID', 'Middle'), ('HIG', 'High'), ('OTH', 'Other')], default='OTH', max_length=3, verbose_name='Education Level'),
        ),
    ]
